### ISSUE TITLE
Can you open source？

### ISSUE THREAD

**Issue by Likenttt** [halbrd/flac-to-mp3#1]
Can you open source？I wanna fork your code, thanks.

**Comment by halbrd** [comment]
Everything is already open. The whole thing is in here: https://github.com/halbrd/flac-to-mp3/blob/master/flac-to-mp3

There's nothing in there that you couldn't write with a little bit of scripting knowledge. Regardless, if it's useful to you, that's great. 🙂

**Comment by Likenttt** [comment]
> Everything is already open. The whole thing is in here: https://github.com/halbrd/flac-to-mp3/blob/master/flac-to-mp3
> 
> There's nothing in there that you couldn't write with a little bit of scripting knowledge. Regardless, if it's useful to you, that's great. 🙂

Good Job！I saw the file without suffix and your instructions below is `./flac2mp3`  previously, so I thought it is a binary file. Actually it is just the source. Thanks a lot.
